# Optional comparison/validation. Never called by run.ps1.
$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot
Push-Location -LiteralPath $repoRoot
try {
    $validator = Join-Path $PSScriptRoot 'tools\actionlint.exe'
    if (-not (Test-Path -LiteralPath $validator)) { throw 'Run transformer-wrapper/install-validator.ps1 first.' }
    $scratch = '.work/compare-' + [DateTime]::UtcNow.ToString('yyyyMMddTHHmmssfffZ')
    New-Item -ItemType Directory -Force -Path $scratch | Out-Null
    function Invoke-Recorded([string]$Executable, [string[]]$Arguments, [string]$Name) {
        # All arguments below are fixed flags or repository-relative paths without spaces.
        # Separate streams avoid publishing PowerShell's invocation/absolute-path error formatting.
        $process = Start-Process -FilePath $Executable -ArgumentList $Arguments -WindowStyle Hidden -Wait -PassThru -RedirectStandardOutput "$scratch/$Name.out" -RedirectStandardError "$scratch/$Name.err"
        $capturedText = [IO.File]::ReadAllText((Join-Path $repoRoot "$scratch/$Name.out")) + [IO.File]::ReadAllText((Join-Path $repoRoot "$scratch/$Name.err"))
        return [PSCustomObject]@{
            ExitCode = $process.ExitCode
            Text = $capturedText.Trim()
        }
    }
    $paths = [ordered]@{
        baseline = 'Outputs/baseline/simple-maven-app.yml'
        native = 'Outputs/modified/native.yml'
        modified = 'Outputs/modified/simple-maven-app.yml'
    }
    $statuses = @{}
    $evidence = @()
    foreach ($name in $paths.Keys) {
        if (-not (Test-Path -LiteralPath $paths[$name])) { throw "Missing $($paths[$name]); run run.ps1 first." }
        $lintResult = Invoke-Recorded $validator @('-no-color','-shellcheck=','-pyflakes=', $paths[$name]) $name
        $lintOutput = $lintResult.Text
        $lintCode = $lintResult.ExitCode
        $statuses[$name] = if ($lintCode -eq 0) { 'PASS' } else { 'FAIL' }
        $evidence += @("### $name", '', '```text', $lintOutput.Trim(), '```', '')
    }
    & docker run --rm --network none --mount "type=bind,source=$repoRoot,target=/work,readonly" -w /work --entrypoint ruby ghcr.io/actions-importer/cli:latest transformer-wrapper/tests.rb $paths.baseline $paths.native $paths.modified simple-maven-app/.gitlab-ci.yml *> "$scratch/assertions.txt"
    $assertionCode = $LASTEXITCODE
    $assertions = Get-Content -LiteralPath "$scratch/assertions.txt" -Raw
    $assertionStatus = if ($assertionCode -eq 0) { 'PASS' } else { 'FAIL' }
    $report = @('# GitHub Actions Importer: baseline and native customization', '',
        'Generated by compare.ps1. This is separate from conversion and does not execute the GitHub workflows.', '',
        '| Check | Result |', '| --- | --- |',
        "| Baseline actionlint | $($statuses.baseline) |",
        "| Native-only actionlint | $($statuses.native) |",
        "| Modified actionlint | $($statuses.modified) |",
        "| Source preservation / native hook checks | $assertionStatus |", '',
        'Native Ruby hooks change checkout, caching and Maven execution; the runner mapping selects ubuntu-24.04. Two explicit postprocessing edits fix the condition and remove the old job container.', '',
        'The native-only syntax failure is retained as evidence of a remaining importer limitation. A passing final lint result does not prove hosted runtime behavior. No hosted execution or cache-service test was performed.', '',
        'Scope: the supplied single-job Maven pipeline. Unsupported hook inputs are rejected. GitLab package hosting, project cancellation settings, and the trivial application test are not improved by these rules.', '',
        '## Static assertions', '', '```text', $assertions.Trim(), '```', '', '## Lint evidence', '')
    $report += $evidence
    foreach ($pair in @(@($paths.baseline,$paths.native), @($paths.native,$paths.modified))) {
        $diffResult = Invoke-Recorded 'git' @('-c','core.autocrlf=false','diff','--no-index','--',$pair[0],$pair[1]) 'diff'
        $diff = $diffResult.Text
        if ($diffResult.ExitCode -gt 1) { throw 'git diff failed.' }
        $report += @("## $($pair[0]) to $($pair[1])", '', '```diff', $diff.Trim(), '```', '')
    }
    $report += @('## File hashes', '', '```text')
    foreach ($name in $paths.Keys) { $report += "$name $((Get-FileHash -LiteralPath $paths[$name]).Hash.ToLower())" }
    $report += @('```', '', 'Actionlint checks expressions and schema; ShellCheck/Pyflakes are disabled. See provenance.json for importer version and configuration hashes.')
    $utf8 = New-Object System.Text.UTF8Encoding($false)
    [IO.File]::WriteAllText((Join-Path $repoRoot 'Outputs/modified/comparison.md'), ($report -join "`n"), $utf8)
    Write-Output "Baseline: $($statuses.baseline); native-only: $($statuses.native); modified: $($statuses.modified); assertions: $assertionStatus"
    Write-Output 'Report: Outputs/modified/comparison.md'
    if ($statuses.modified -ne 'PASS' -or $assertionCode -ne 0) { exit 1 }
} finally { Pop-Location }
